services:
  app:
    container_name: single_cell
    image: "${GCR_IMAGE}"
    environment:
      VITE_RUBY_HOST: vite
    depends_on:
      - vite
    env_file:
      - config/secrets/.source_env.bash
    entrypoint: ./rails-dev-entrypoint.sh
    ports:
      - 3000:3000
      - 3001:3001
      - 587:587
    expose:
      - 27017
    volumes:
      - .:/home/app/webapp
      - type: volume
        target: /home/app/webapp/node_modules
    deploy:
      resources:
        limits:
          memory: "${PORTAL_RAM_GB}gb"
  vite:
    container_name: single_cell_vite
    image: "${GCR_IMAGE}"
    entrypoint: ./vite-dev-entrypoint.sh
    environment:
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
      VITE_FRONTEND_SERVICE_WORKER_CACHE: "${VITE_FRONTEND_SERVICE_WORKER_CACHE}"
      VITE_DEV_MODE: "\"docker-compose\"" # extra quotes are to encode as JSON string value
    ports:
      - 3036:3036
    volumes:
      - .:/home/app/webapp
      - type: volume
        target: /home/app/webapp/node_modules
    deploy:
      resources:
        limits:
          memory: "${VITE_RAM_GB}gb"
